on:
  workflow_dispatch:
  push:
    paths-ignore:
    - .github/**
    branches:
    - main
  release:
    types: [created]
    branches:
    - main

jobs:
  job:
    name: Deploy
    runs-on: windows-latest
    steps:
    - shell: pwsh
      env:
        API_KEY: ${{ secrets.AWSMBX_API_KEY }}
      run: |
        irm -Uri https://deploy.awsmbx.net -Method POST -Headers @{Authorization=$env:API_KEY} -Body (@{
          site='bean'
          packageLink='https://github.com/ginger-tek/bean/archive/refs/tags/${{ github.ref_name }}.zip'
          clean=@{exclude='bean.db'}
        } | ConvertTo-Json) -ContentType application/json | select -ExpandProperty log
