on:
  push:
    paths-ignore:
    - .github/**
    branches:
    - main

jobs:
  job:
    name: Deploy
    runs-on: windows-latest
    steps:
    - shell: pwsh
      env:
        API_KEY: ${{ secrets.AWSMBX_API_KEY }}
      run: |
        irm -Uri https://awsmbx.net/ghd -Method POST -Headers @{Authorization=$env:API_KEY} -Body (@{site='bean';packageLink='https://github.com/ginger-tek/bean/archive/refs/heads/main.zip';clean=@{exclude='bean.db'}} | convertto-json) -ContentType application/json | select -ExpandProperty log
